version: "3"
services:

  www:
    image: nginx
    ports:
      - "80:80"

  mysql:
    image: mysql
    entrypoint: ["/entrypoint.sh", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: "yolo"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - /home/centos/config.inc.php:/etc/phpmyadmin/config.inc.php
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
