version: "3.6"
services:

  nginx:
    image: nginx
    ports:
      - published: 80
        target: 80
        mode: host
      - published: 443
        target: 443
        mode: host
      - published: 9000 # Temporary for phpmyadmin; recommended to remove for a URL
        target: 9000    # Temporary for phpmyadmin; recommended to remove for a URL
        mode: host
    volumes:
      - ./single_files/dhparam.pem:/dhparam.pem         # Custom DH parameters
      - ./single_files/nginx.conf:/etc/nginx/nginx.conf # Custom NGINX config file
      - ./nginx_conf.d:/etc/nginx/conf.d
      - ssl_challenge:/ssl_challenge
      - ssl:/ssl

  mysql:
    image: mysql
    volumes:
      - sql_storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "fizz"
    entrypoint: ["/entrypoint.sh", "--default-authentication-plugin=mysql_native_password"]
    deploy:
      resources:
        limits:
          memory: 450M

  sample-app:
    image: sample-app
    volumes:
      - ./logs:/usr/src/app/log
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./single_files/config.inc.php:/etc/phpmyadmin/config.inc.php # Custom phpMyAdmin config file
      - ./single_files/header.twig:/www/templates/login/header.twig  # Mod to hide the "https mismatch" error
      - ./single_files/index.php:/www/index.php                      # Mod to hide the SSL status
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
    depends_on:
      - mysql

volumes:
  sql_storage:
  ssl_challenge:
  ssl:
